allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"nfs-nas-v3"},"mountOptions":["hard","nfsvers=3","rsize=1048576","wsize=1048576","timeo=600"],"parameters":{"server":"100.100.100.120","share":"/volume1/share"},"provisioner":"nfs.csi.k8s.io","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2025-06-20T08:31:34Z"
  name: nfs-nas-v3
  resourceVersion: "7972637"
  uid: 81847db0-0717-4bfc-aa44-08b1c2afc778
mountOptions:
- hard
- nfsvers=3
- rsize=1048576
- wsize=1048576
- timeo=600
parameters:
  server: 100.100.100.120
  share: /volume1/share
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
