
# type "user" or "group"
# - user  -> pvc-<username>-share  storageClass: nfs-user-storage
# - group -> pvc-<username>-group-share  storageClass: nfs-group-storage
type: user

basePath: /volume1/share
username: jy
nfsServer: 192.168.2.30
storageSize: 20Gi

config:
  namespace: cssh

