apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.config.namespace }}
  annotations:
    nfs.io/type: "{{ .Values.type }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.storageSize }}"
  storageClassName: "{{ .Values.storageClass }}"
  volumeMode: Filesystem
