apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerssh-config-server
  namespace: containerssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerssh-config-server
  template:
    metadata:
      labels:
        app: containerssh-config-server
    spec:
      containers:
        - name: config-server
          image: containerssh-config-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

