apiVersion: v1
kind: Service
metadata:
  name: containerssh-config-service
  namespace: containerssh
spec:
  type: NodePort
  selector:
    app: containerssh-config-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30082

