apiVersion: v1
data:
  config.yaml: |
    ssh:
      listen: "0.0.0.0:2222"
      hostkeys:
        - /etc/containerssh/host.key
      banner: |
        Welcome to ContainerSSH!
        Enter any username and password to continue.

    auth:
      password:
        webhook:
          url: http://containerssh-auth-service.containerssh.svc.cluster.local/password
      pubkey:
        webhook:
          url: http://containerssh-auth-service.containerssh.svc.cluster.local/pubkey
      timeout: 60s

    backend: kubernetes
    kubernetes:
      connection:
        host: kubernetes.default.svc
        cacertFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

      pod:
        metadata:
          namespace: containerssh
          labels:
            app: containerssh-guest
            managed-by: containerssh
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - name: shell
            image: containerssh/containerssh:v0.5
            command:
              - /bin/bash
            stdin: true
            tty: true
            env:
              - name: USER
                value: guest
              - name: HOME
                value: "/home/guest"
              - name: SHELL
                value: "/bin/bash"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
            volumeMounts:
              - name: user-home
                mountPath: /home/share
                readOnly: false
          volumes:
            - name: user-home
              persistentVolumeClaim:
                claimName: pvc-guest-share
          restartPolicy: Never

    log:
      level: "info"
      format: "text"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: containerssh
    meta.helm.sh/release-namespace: containerssh
  creationTimestamp: "2025-07-14T14:56:55Z"
  labels:
    app: containerssh
    app.kubernetes.io/managed-by: Helm
  name: containerssh-config
  namespace: containerssh
  resourceVersion: "5740586"
  uid: d0cd662e-a36c-4cec-aed4-7fd08990b7af
