image:
  repository: dguailab/config-server
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30082

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  nfsAddress: "192.168.2.30"

nfs:
  server: "192.168.2.30"
  path: "/volume1/share"

security:
  sudoAllowedCommands: ""


config:
  namespace: ailab-infra


namespace: ailab-infra

cleanup:
  image: config-server:latest

redis:
  host: redis-bg-master.ailab-infra.svc.cluster.local
  port: 6379

# config-server를 배포할 노드 고정
# csid-dgu-desktop은 control-plane 노드이므로 아래 tolerations와 함께 사용해야 한다.
nodeSelector:
  kubernetes.io/hostname: csid-dgu-desktop

# 데스크탑의 NoSchedule taint를 허용
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

