image:
  repository: config-server
  tag: v1
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 9732

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  nfsAddress: "100.100.100.120"

nfs:
  server: "100.100.100.120"
  path: "/volume1/share/kube_share"


config:
  namespace: cssh


namespace: cssh

cleanup:
  image: config-server:v1

redis:
  host: redis-bg-master.cssh.svc.cluster.local
  port: 6379

