apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-background-pods
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: {{ .Values.cleanup.image }}
            command: ["python", "/app/cleanup_cronjob.py"]
            volumeMounts:
              - name: app-code
                mountPath: /app
            env:
              - name: REDIS_HOST
                value: {{ .Values.redis.host }}
              - name: REDIS_PORT
                value: "{{ .Values.redis.port }}"
          restartPolicy: OnFailure
          volumes:
            - name: app-code
              configMap:
                name: config-server-scripts

