apiVersion: v1
kind: ConfigMap
metadata:
  name: containerssh-config
  namespace: {{ .Values.config.namespace }}
  labels:
    app: containerssh

data:
  config.yaml: |
    ssh:
      listen: "0.0.0.0:2222"
      hostkeys:
        - /etc/containerssh/host.key
      banner: |
        Welcome to ContainerSSH!
        Enter any username and password to continue.

    auth:
      password:
        method: webhook
        webhook:
          url: {{ include "containerssh.authPasswordUrl" . }}
      publicKey:
        method: webhook
        webhook:
          url: {{ include "containerssh.authPubkeyUrl" . }}
      timeout: {{ .Values.config.authTimeout }}

    security:
      forwarding:
        reverseForwardingMode: enable
        forwardingMode: enable
        socketForwardingMode: enable
        socketListenMode: enable

    configserver:
        url: {{ include "containerssh.configServerUrl" . }}
        timeout: {{ .Values.config.configServerTimeout }}


    log:
      level: "{{ .Values.log.level }}"
      format: "{{ .Values.log.format }}"

