apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: containerssh
    meta.helm.sh/release-namespace: containerssh
  creationTimestamp: "2025-07-14T14:56:55Z"
  generation: 7
  labels:
    app.kubernetes.io/managed-by: Helm
  name: containerssh
  namespace: containerssh
  resourceVersion: "5830732"
  uid: f1f72c15-520d-40e4-9035-6d04c4a55c58
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: containerssh
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-15T05:41:16+09:00"
      creationTimestamp: null
      labels:
        app: containerssh
    spec:
      containers:
      - image: containerssh/containerssh:v0.5
        imagePullPolicy: IfNotPresent
        name: containerssh
        ports:
        - containerPort: 2222
          name: ssh
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/containerssh/host.key
          name: hostkey
          readOnly: true
          subPath: host.key
        - mountPath: /etc/containerssh/config.yaml
          name: config
          readOnly: true
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: containerssh
      serviceAccountName: containerssh
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hostkey
        secret:
          defaultMode: 420
          secretName: containerssh-hostkey
      - configMap:
          defaultMode: 420
          name: containerssh-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-15T03:04:38Z"
    lastUpdateTime: "2025-07-15T03:04:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-15T02:58:28Z"
    lastUpdateTime: "2025-07-15T03:04:38Z"
    message: ReplicaSet "containerssh-69cb54689c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
