apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.config.namespace }}
  name: containerssh-role
  labels:
    app: containerssh
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

# PVC 권한 추가
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: containerssh-rolebinding
  namespace: {{ .Values.config.namespace }}
  labels:
    app: containerssh
subjects:
- kind: ServiceAccount
  name: containerssh
  namespace: {{ .Values.config.namespace }}
roleRef:
  kind: Role
  name: containerssh-role
  apiGroup: rbac.authorization.k8s.io
