{{- if .Values.hostKey.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hostKey.secretName }}
  namespace: {{ .Values.config.namespace }}
type: Opaque
data:
  host.key: {{ .Files.Get .Values.hostKey.privateKeyPath | b64enc }}
{{- end }}

