apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-image-store
  namespace: {{ .Values.config.namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.imageStore.size }}
  storageClassName: {{ .Values.storageClass }}
  volumeMode: Filesystem
