apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Values.username }}-share
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfsServer }}
    path: /294t/dcloud/share/user-share/{{ .Values.username }}
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.username }}-share
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-{{ .Values.username }}-share
  storageClassName: ""

