apiVersion: v1
kind: ConfigMap
metadata:
  name: containerssh-config
  namespace: containerssh
  labels:
    app: containerssh
data:
  config.yaml: |
    ssh:
      # 서버 설정
      listen: "0.0.0.0:2222"
      # 호스트키 설정
      hostkeys:
        - /etc/containerssh/host.key
      # SSH 배너 (선택사항)
      banner: |
        Welcome to ContainerSSH!
        Enter any username and password to continue.
    
    # 인증 설정 - 단순하게 auth 서비스 URL만 지정
    auth:
      url: http://containerssh-auth-service.containerssh.svc.cluster.local/password
      timeout: 60s
    
    # 백엔드 설정
    backend: kubernetes
    kubernetes:
      connection:
        host: kubernetes.default.svc
        cacertFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      
      # Pod 설정
      pod:
        metadata:
          namespace: containerssh
          labels:
            app: containerssh-guest
            managed-by: containerssh
        spec:
          # 보안 컨텍스트
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - name: shell
            image: containerssh/containerssh-guest-image
            command:
            - /bin/bash
            stdin: true
            tty: true
            # 환경 변수 설정
            env:
            - name: USER
              value: "guest"
            - name: HOME
              value: "/home/guest"
            - name: SHELL
              value: "/bin/bash"
            # 리소스 제한
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
            # 보안 컨텍스트
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL
          
          # Pod 자동 정리 (1시간 후)
          activeDeadlineSeconds: 3600
          restartPolicy: Never
    
    # 로깅 설정
    log:
      level: info
      format: text
