apiVersion: v1
kind: Service
metadata:
  name: containerssh
  namespace: containerssh
  labels:
    app: containerssh
spec:
  type: NodePort
  selector:
    app: containerssh
  ports:
  - name: ssh
    port: 2222
    targetPort: 2222
    protocol: TCP
    # nodePort는 자동 할당되도록 설정
    # 특정 포트를 원한다면 nodePort: 30222 와 같이 지정
